#!/bin/bash

############################################################################
# Squid Proxy Installer (SPI)                                              #
# Version: 3.0 Build 2017                                                  #
# Branch: Stable                                                           #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Author: Hidden Refuge (© 2014 - 2017)                                    #
# License: MIT License                                                     #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# GitHub Repo: https://github.com/snake4life/spi/                          #
# SPI Wiki: https://github.com/snake4life/spi/wiki                         #
############################################################################

# Declaring a few misc variables
vspiversion=3.0 # SPI version
vspibuild=2017 # SPI build number
vbranch=Stable # SPI build branch
vsysarch=$(getconf LONG_BIT) # System architecture

# Function for iptables rules (Ubuntu)
firew2 ()	{
	# Opening default Squid port 1337 for clients to connect
	iptables -I INPUT -p tcp --dport 1337 -j ACCEPT
	# Saving firewall rules
	iptables-save
}

# Function for Ubuntu
ubt ()	{
	# Updating package database
	apt-get update
	# Installing necessary packages (Squid, apache2-utils for htpassword and dependencies)
	apt-get install apache2-utils squid3 -y
	# Asking user to set a username via read and writing it into $usrn
	read -e -p "Your desired username: " usrn
	# Creating user with username from $usrn and asking user to set a password
	htpasswd -c /etc/squid/passwd $usrn
	# Downloading Squid configuration
	wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/snake4life/spi/master/spi-ubuntu.conf --no-check-certificate
	# Creating empty blacklist.acl file for further blacklisting entries
	touch /etc/squid/blacklist.acl	
	# Restarting Squid and enabling its service
	service squid restart && update-rc.d squid defaults
	# Running function firew2
	firew2
}

# Default function with information
dinfo ()	{
	echo "Squid Proxy Installer $vspiversion Build $vspibuild"
	echo "You are using builds from the $vbranch branch"
	echo ""
	echo "Usage: bash spi <option>"
	echo "Example (Ubuntu): bash spi -ubuntu"
	echo ""
	echo "Options:"
	echo "-ubuntu  -- Ubuntu"
	echo ""
}

# Checking $1 and running corresponding function
case $1 in
	'-ubuntu') # If option "-ubuntu" run function ubt
		ubt;; # Ubuntu
	*) # If option empty or non existing run function info
		dinfo;; # Default, information about available options and et cetera
esac
